spring.application.name: spatial-jpa-service

server:
  port: 8080
  servlet:
    context-path: /spatial

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/geo_db?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: test1234
    platform: MySQL
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: false
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.mysql.MySQL56SpatialDialect




